version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 6868:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 101001
      POSTGRES_DB: nest
  test-db:
    image: postgres:latest
    ports:
      - 6767:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 101001
      POSTGRES_DB: nest